### ISSUE TITLE
No 'rosidl_typesupport_c' found on AlmaLinux 8

### ISSUE THREAD

**Issue by christianrauch** [ros2/rosidl_typesupport#162]
Building any minimal node (e.g. `examples_rclcpp_minimal_publisher`) on AlmaLinux 8 fails with `No 'rosidl_typesupport_c' found`, even though package `ros-humble-rosidl-typesupport-c` is installed.

## Bug report

**Required Info:**

- Operating System:
  - AlmaLinux 8
- Installation type:
  - binaries
- Version or commit hash:
  - 2.0.2
- DDS implementation:
  - 
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Use the following GitHub CI pipeline (https://github.com/christianrauch/action-ros-ci-almalinux-test/tree/minimal):
```yaml
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: "AlmaLinux 8 / humble"
    runs-on: ubuntu-latest
    container:
      image: almalinux:8

    steps:
      - uses: ros-tooling/setup-ros@v0.7

      - name: generate repos file
        run: |
          cat << EOF > sources.repos
          repositories:
            src/examples:
              type: git
              url: https://github.com/ros2/examples.git
              version: humble
          EOF

      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: examples_rclcpp_minimal_publisher
          target-ros2-distro: humble
          vcs-repo-file-url: sources.repos
```

#### Expected behavior

`examples_rclcpp_minimal_publisher` should compile without issues.

#### Actual behavior

The build fails with `No 'rosidl_typesupport_c' found`:
```
Starting >>> examples_rclcpp_minimal_publisher
--- output: examples_rclcpp_minimal_publisher
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 1.3.11 (/opt/ros/humble/share/ament_cmake/cmake)
-- Found Python3: /usr/bin/python3 (found version "3.6.8") found components: Interpreter 
-- Override CMake install command with custom implementation using symlinks instead of copying resources
-- Found rclcpp: 16.0.11 (/opt/ros/humble/share/rclcpp/cmake)
-- Found rosidl_generator_c: 3.1.6 (/opt/ros/humble/share/rosidl_generator_c/cmake)
-- Found rosidl_adapter: 3.1.6 (/opt/ros/humble/share/rosidl_adapter/cmake)
-- Found rosidl_generator_cpp: 3.1.6 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
CMake Error at /opt/ros/humble/share/rosidl_typesupport_c/cmake/get_used_typesupports.cmake:35 (message):
  No 'rosidl_typesupport_c' found
Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_typesupport_c/cmake/rosidl_typesupport_c-extras.cmake:8 (get_used_typesupports)
  /opt/ros/humble/share/rosidl_typesupport_c/cmake/rosidl_typesupport_cConfig.cmake:41 (include)
  /opt/ros/humble/share/builtin_interfaces/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/humble/share/builtin_interfaces/cmake/builtin_interfacesConfig.cmake:41 (include)
  /opt/ros/humble/share/libstatistics_collector/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/humble/share/libstatistics_collector/cmake/libstatistics_collectorConfig.cmake:41 (include)
  /opt/ros/humble/share/rclcpp/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/humble/share/rclcpp/cmake/rclcppConfig.cmake:41 (include)
  CMakeLists.txt:14 (find_package)
```

See full log: [logs_32542829113.zip](https://github.com/user-attachments/files/18275750/logs_32542829113.zip)
